on:
  push:
    branches:
      - dev
name: Build
jobs:
  make:
    name: Build and Upload Sileo
    runs-on: macos-latest
    steps:
      - name: Wakeup babe
        uses: elihwyma/nightly-updater@v1
        with:
          message-title: Wake up Babe
          webhook: ${{ secrets.WEBOOK }}
      
